export const GET_BLOGS_START = "GET_BLOGS_START";
export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS";
export const GET_BLOGS_ERROR = "GET_BLOGS_ERROR";

////////////////////////GET_SINGLE_BLOGS///////////////

export const GET_SINGLE_BLOGS_START = "GET_SINGLE_BLOGS_START";
export const GET_SINGLE_BLOGS_SUCCESS = "GET_SINGLE_BLOGS_SUCCESS";
export const GET_SINGLE_BLOGS_ERROR = "GET_SINGLE_BLOGS_ERROR";
